# -*- coding: utf-8 -*-
"""English display titles for Beta files (673–809). Key = file number."""
from __future__ import annotations

TITLES: dict[int, str] = {
    673: "Jason Todd in Strange Lab - Café and missing persons",
    680: "Magic and Brother Bond - Worlds where only Jason transforms",
    684: "Child of Light in Gotham - Sky crossover with wings",
    685: "Gotham Arcana Cult - Magic cards and portal hunt",
    686: "Dick Meets Ghost Robin - Therapy and real Jason",
    687: "Jason Hides Cute Ghost Form - Shame after return",
    688: "Tokyo Mew Mew Crossover - Jason becomes catgirl",
    689: "Batman AU Without Alfred - Bruce breaks, Dick Nightwing",
    690: "Batfamily vs Bruce's Dark Magic - Cursed temple",
    691: "Dick De-aged in Zatanna Trap - Still captive",
    692: "Damian De-aged Bat Wings - Humanity vs wild pack",
    694: "Jason and Touch Hunger - Won't ask for hugs",
    695: "Jason and Physical Distance - Hurt comfort plan",
    696: "Unknown Ghost Chick in Cave - Robin bird halfling",
    699: "Batfamily Magic Body-Swap Storm - Jason stabilizer",
    700: "GIW Halfla Jason Concept - Danny Phantom DC crossover",
    701: "Shadow Chimera Bite - Jason becomes kitten",
    702: "Jason Becomes Dream Keeper - Ritual heart and nightmares",
    703: "Batman Missing Shadow Trapped - Ghosts of Gotham",
    704: "Jason Alien Kidnapping - Accidental teleport humor",
    705: "Jason Returns as Aster - Winged meta child amnesia",
    706: "Crystal Throw Transformations - Shadows and glowing eyes",
    707: "Red Hood in Japan - Teen Robin body isekai",
    708: "GIW Halfa Mission - Family escape plan",
    709: "Ghost at Stephanie's Party - Invisible comfort",
    710: "Wake in Alternate Bodies - Wrong reality details",
    711: "Jason Wounded No Heroes AU - Medics baffled",
    712: "Warehouse Kitten Bite - Child cat hybrid",
    713: "Dream Keeper Mask Removed - Ritual cost",
    714: "Street Kids Vanishings - Jason parallel investigation",
    715: "Magic Card Cult Portal - Card world entities",
    716: "Danny Summer at Waynes - DP DC cousins",
    717: "Jason Family Antidote Form - Cute half-Robin under threat",
    718: "Jason Becomes Falcon Hero - Magic child eight to ten",
    719: "Red Hood De-aged by Artifact - Ruins child return",
    721: "Enemy Appears Little Robin - Blue eyes ritual",
    722: "Man Becomes Bird Teen - Wings and feathers",
    723: "Jason Star Fledgling - Emotion portal warehouse",
    724: "Jason Returns to Batcave - Portal aftermath",
    725: "Dick and Roof Ghost Robin - Therapy reveal",
    726: "Kitten Trapped by Heroes - Jason unknown child",
    727: "Jason Meets Batman with Artifact - Unrecognized wounded",
    728: "Bruce Wakes Talon AU Manor - Soft dawn not Gotham",
    729: "GIW Kidnap Prequel - Experiments before Red Hood",
    730: "Batfamily on Moon Ruins - Zatanna shadows",
    731: "Jason and Dick World Travel Alt - Magic only Jason",
    732: "Jason Cyan Two Forms - Adult Hood and feather child",
    733: "Mahou Shoujo Mew Worlds - Shadow League artifact",
    734: "Dream Keeper Long Prose - Variant of 702",
    735: "Red Hood and Spoiler Portal - Cultists stuck together",
    736: "Batfamily Strange Transformations - Magic shock",
    737: "Another Transformation Wave - Cave comedy and hurt",
    738: "Sun Orb De-age Five Chapters - Fifteen Robin feathers",
    739: "Jason Magic Trials Series - Artifacts and family",
    741: "Batman Suspects Betrayal - Jason isolated trust break",
    742: "Bruce and Jason Love and Conflict - Father and son",
    743: "Jason Nightmare Reality - Family rescue angst",
    744: "Wild Batfamily AU - Chirping Robins behind glass",
    745: "Bruce Jason Psychology - Trauma and Red Hood",
    746: "Wild Cave Jason Third Person - Flee chirp language",
    747: "World of Birds and Robins - Flock laws isekai",
    748: "Red Hood in Wrong Nest - Flock metaphor acceptance",
    749: "Bird Flock Alchemy Fantasy - World and role plan",
    750: "Jason in Bird World - Hierarchy wings identity",
    751: "Batfamily Hunts White Ghost - Unaware it is Jason",
    752: "Gotham Entities New Hero - City lore clash",
    753: "Red Hood Isekai No Batman - Survival and home",
    754: "GIW Makes Jason Halfa - Lab capture plan",
    755: "Transformation Wave in Cave - Mutual aid chaos",
    756: "Jason Magic World Isekai - New rules leave Gotham",
    757: "Portal Isekai Opening - Jason crossover start",
    758: "Smuggler Chase Magic Wound - Body status twist",
    759: "Jason Todd Version Portraits - Reference collection",
    760: "Bruce Jason Return to Darkness - Triggers and past",
    761: "Jason Magic Crystal - Family artifact Hood",
    762: "Jason Character Guide - Innate learned amnesia notes",
    763: "Jason Sudden Teen Again - Family Robin body",
    764: "Darkness Over Gotham Mass Transform - Family bonds",
    765: "GIW Ambush Ghost Zone - Robin suit panic DP",
    766: "Jason Wakes in Forest Hood Gear - Disorientation",
    767: "Dream of Batfamily Becomes Real - Sleep and magic",
    768: "Shimada Brothers After Conflict - Overwatch concept",
    769: "Shimada Dragons Not Spirits - Overwatch AU rules",
    770: "Genji After Bridge River - Overwatch survival guilt",
    771: "Within Reach of Hand - Overwatch brothers distance",
    772: "Heir and Donor - Overwatch clan blood metaphor",
    773: "Shimada Brothers Lab Escapees - Overwatch AU plan",
    774: "Overwatch Universe Concept - Team roles setting",
    775: "Under Dragon Temple - Overwatch clan artifact",
    776: "Genji Hatred After Forgiveness - Overwatch brotherhood",
    777: "Overwatch Mission Roster Scenes - Team slice scenes",
    778: "Dragon Shard - Overwatch Shimada artifact",
    779: "Two Dragons One Egg - Overwatch child bodies AU",
    780: "Dragon Under Skin - Overwatch pre-Dragons short",
    781: "Golden Dragon Overwatch AU - Clan backstory",
    782: "Dragon Heart - Overwatch guilt duty magic",
    783: "Accidental Gotham Ritual on Jason - Transformation plan",
    784: "Dick Crawls Home at 3 AM - Quiet hurt comfort",
    785: "DC Canon Timeline Setting - Event reference list",
    786: "White Boy on Cameras - Ghost meta investigation",
    787: "Second Sign - Omen artifact prophecy",
    788: "Overwatch Fandom Alt World - Setting ideas",
    789: "Red Hood and Red Riding Hood - Fairy tale magic",
    790: "Hero of Heart in White - Artifact hope symbol",
    791: "Second Year That Never Was - Time anomaly memory",
    792: "Fall into Bright World Ch1 - Isekai magic opening",
    793: "Red Hood vs Therapy Deck - Magic absurd battle",
    794: "Fledgling in Bat House - Little Jason at manor",
    795: "Seven Days on Four Paws - Cat body cave comedy",
    796: "Jason Won't Raise Topic at Dinner - Family secret",
    797: "Alfred Dead Before Bruce - Batfamily break AU",
    798: "Last Words Not His Name - Jason dies on mission",
    799: "Too High - Flight artifact fall metaphor",
    800: "Ghost Chick in Cave Variant - Family doesn't know Jason",
    801: "Jason Fights Family One Chapter - Night after argument",
    802: "Shadow Entities No Weapon Works - Family weak point",
    803: "GIW Halfa Fanfic Structure - Experiment outline",
    804: "It Didn't Work - Failed ritual pivot",
    805: "Albino Animal Heists - Seven-year fox Jason",
    806: "Plush Cat Protocol - Magic child form humor",
    807: "Steph Wakes Wrong Place - Magic after bachelorette",
    808: "Batfamily Mission Chapter - Bruce Dick Damian team",
    809: "Street Kids Missing Investigation - Jason solo case",
    810: "Batfamily Body-Swap Loop - AU world concepts",
    811: "Child Jason in Sun Pit - Ghost family movie night",
    812: "WINX Life Crystal Door - Lazarus Pit burned away",
    813: "Medallion De-ages Jason to Seven - Calm without Pit rage",
    818: "Green Light Erases Past - Robin identity stripped artifact",
    819: "Kingdom Hearts Hope Wing - First keyblade transformation",
    880: "Winged Humanity AU - Hospital isekai setting bible",
}

# 819 stays plain filename per vault convention
KEEP_PLAIN = {819}
